var turn = 0;
var money = 10;
var people = 10;
var people1;
var pollution = 0;
var pollution_buying = 1;
var trees = [0, 0, 0];
var trees_buying = 1;
var army = 0;
var army_buying = 1;
var reset = false;
var Over = "";
var pollution_cleaners = 0;
var pollution_cost = 15;
var tree_cost = 10;
var best_score = 0;
var pollution_decrease =0;
